using System.Windows.Forms;
using Eplan.EplApi.Scripting;

public partial class formTemplate : System.Windows.Forms.Form
{

    #region generated by the Windows Form Designer Code

    /// <summary>
    /// Required designer variable.
    /// </summary>
    private System.ComponentModel.IContainer components = null;

    /// <summary>
    /// clean up resources used.
    /// </summary>
    /// < param  name = " disposing " > True if managed resources
    /// to be deleted; False otherwise. </ param >
    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
        {
            components.Dispose();
        }
        base.Dispose(disposing);
    }

    /// <summary>
    /// Required method for Designer support.
    /// The contents of this method does not involve the Code Editor
    /// be changed.
    /// </summary>
    private void InitializeComponent()
    {
        this.SuspendLayout();
        // 
        // formTemplate
        // 
        this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
        this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
        this.ClientSize = new System.Drawing.Size(292, 273);
        this.Name = "formTemplate";
        this .StartPosition =
            System.Windows.Forms.FormStartPosition.CenterScreen;
        this .Text = " template " ;
        this.ResumeLayout(false);

    }

    public formTemplate()
    {
        InitializeComponent();
    }

    #endregion

    [Start]
    public void Function()
    {
        formTemplate  frm = new  formTemplate ();
        frm.ShowDialog();

        return;
    }
}